# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3535cd00215ee97002dcd5aa08eca74cdbae4fc0287f5e02718c5bb7fcfaf160292da6efdd73e4f646e801b6fdab7a8bb5f91406228f10e9c355f0b283807258

test:
  secret_key_base: 6fe6946b2f60d391c67555c6a2e70b7619f1a4ad9cb5b6aaa93ea37ebbaa6cb782465e3e3b1c921f3283934e206e797578609488910b2773ff4548c968a6698c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
